### ISSUE TITLE
Engine Temp Reads & Logs '-' (minus)

### ISSUE THREAD

**Issue by kenrox** [stelian42/HarleyDroid#3] opened 2011-06-23 13:50 UTC
the engine temp values turn to minus at any given point. (both on display and log file)
like 50,51, -52,-53..
never had this issue in my c# app. so i think it's not about the incoming efi data.

log file
http://kenrox.org/bikez/harley-20110623105809.log.gz

disclaimer : speed , rpm and location values are logged on a different planet entirely for educational/scientific purposes. no harm done to animals (oops aliens) ;)

**Comment by stelian42** [comment] 2011-06-23 14:38
Hmm, my (now broken) Sportster was a pre-EFI carburated one which didn't send engine temp signals on J1850 bus. So that code was never tested.

Looking at the code I think I got it. Java 'byte' sucks !

<pre>
diff --git a/src/org/harleydroid/J1850.java b/src/org/harleydroid/J1850.java
index 088e2d1..e982ad9 100644
--- a/src/org/harleydroid/J1850.java
+++ b/src/org/harleydroid/J1850.java
@@ -113,7 +113,7 @@ public class J1850 {
                else if (x == 0x48291002)
                        hd.setSpeed(y);
                else if (x == 0xa8491010)
-                       hd.setEngineTemp(in[4]);
+                       hd.setEngineTemp((int)in[4] & 0xff);
                else if (x == 0xa83b1003) {
                        if (in[4] != 0) {
                                int gear = 0;
</pre>

**Comment by stelian42** [comment] 2011-06-24 08:10
Can you confirm the above patch fixes the issue ?

**Comment by kenrox** [comment] 2011-06-24 11:23
will test it tonight.

**Comment by stelian42** [comment] 2011-06-24 11:25
ok.

On Fri, Jun 24, 2011 at 04:23:12AM -0700, kenrox wrote:

> will test it tonight.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stelian42/HarleyDroid/issues/3#issuecomment-1431747

## 

Stelian Pop stelian@popies.net

**Comment by kenrox** [comment] 2011-06-24 19:59
oh blast!
went for test ride. but the log file is giving a crc fail.
http://www.kenrox.org/stuff/hdroid_log_crc_err.jpg

can't confirm the temp readings visually also 'cause two of my tablet holder pins are missing. so the tablet was on my backpack.

in field testing, it happens). will test again tomorrow.

**Comment by kenrox** [comment] 2011-06-25 11:46
temp readings back to normal. patch is working.

www.kenrox.org/bikez/harley-20110625142634615.log.gz

**Comment by stelian42** [comment] 2011-06-27 12:08
CRC fail problems are caused by HarleyDroid crashing and thus not closing the zip archive correctly. I've seen this once or twice but never been able to find out why it happen (I suspect a crash in the bluetooth stack more that in HarleyDroid itself...)

Thanks for the temperature tests. Patch commited.

**Closed as completed by stelian42** 2011-06-27 12:08 UTC
